image: python:3.10.11-bullseye

before_script:
  ## Install packages
  - python -m venv .venv/
  - source .venv/bin/activate
  - pip install -e .

test:
  stage: test
  before_script:
    - pip install -e .[test]
  script:
    - pytest --durations=0 --cov=src/translatex -sv
    - coverage html -d public/coverage
  coverage: '/TOTAL.*\s+(\d+\%)/'
  artifacts:
    paths:
      - public
  tags:
    - docker

pages:
  stage: deploy
  before_script:
    - apt -q update && apt -q install graphviz
    - pip install -e .[doc]
  script:
    - sphinx-build -b html docs/source/ public/
  only:
    - main
  artifacts:
    paths:
      - public
  tags:
    - docker