image: python

before_script:
  ## Install packages
  - python -m venv .venv/
  - source .venv/bin/activate
  - pip install -e .

test:
  stage: test
  script:
    - pip install -e .[test]
    - pytest --durations=0 --cov=src/translatex -sv
    - coverage html -d public/coverage
  coverage: '/TOTAL.*\s+(\d+\%)/'
  tags:
    - docker
  artifacts:
    paths:
      - public
      
pages:
  stage: deploy
  script:
    - pip install -e .[doc]
    - sphinx-build -b html docs/source/ public/
  only:
    - main
  artifacts:
    paths:
      - public
  tags:
    - docker