repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: pytest
        name: pytest (standard-test)
        stages: [push]
        language: system
        entry: pytest -sv
        pass_filenames: false
        always_run: true
      - id: pytest-ext
        name: pytest (extended-test)
        stages: [manual]
        language: system
        entry: pytest -sv --runapi
        pass_filenames: false
        always_run: true
